from __future__ import annotations

from enum import StrEnum


class Authority(StrEnum):
    A = "A"
    B = "B"
    C = "C"
    PROVISIONAL = "PROVISIONAL"

    @property
    def trusted(self) -> bool:
        return self in {Authority.A, Authority.B, Authority.C}


class Confidence(StrEnum):
    CONFIRMED = "CONFIRMED"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class EvidenceKind(StrEnum):
    ISSUE_NORMATIVE = "ISSUE_NORMATIVE"
    ISSUE_WITNESS = "ISSUE_WITNESS"
    PUBLIC_TEST = "PUBLIC_TEST"
    DOCUMENTATION = "DOCUMENTATION"
    TYPE_CONTRACT = "TYPE_CONTRACT"
    CURRENT_BEHAVIOR = "CURRENT_BEHAVIOR"
    PRESERVATION_BEHAVIOR = "PRESERVATION_BEHAVIOR"
    STATIC_INFERENCE = "STATIC_INFERENCE"
    DYNAMIC_OBSERVATION = "DYNAMIC_OBSERVATION"
    MODEL_HYPOTHESIS = "MODEL_HYPOTHESIS"
    CONTRADICTION = "CONTRADICTION"


class SemanticNodeKind(StrEnum):
    OBSERVATION = "OBSERVATION"
    NORMATIVE_REQUIREMENT = "NORMATIVE_REQUIREMENT"
    SEMANTIC_HYPOTHESIS = "SEMANTIC_HYPOTHESIS"
    PRESERVATION_CONTRACT = "PRESERVATION_CONTRACT"
    EVIDENCE = "EVIDENCE"
    CONTRADICTION = "CONTRADICTION"
    UNKNOWN = "UNKNOWN"


class HypothesisLifecycle(StrEnum):
    VIABLE = "VIABLE"
    SUPPORTED = "SUPPORTED"
    CONTESTED = "CONTESTED"
    REFUTED = "REFUTED"
    UNIDENTIFIABLE = "UNIDENTIFIABLE"


class OracleLifecycle(StrEnum):
    ACTIVE = "ACTIVE"
    CONTESTED = "CONTESTED"
    DOWNGRADED = "DOWNGRADED"
    REVOKED = "REVOKED"


class OutcomeStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"
    BLOCKED = "BLOCKED"
    UNKNOWN_ORACLE = "UNKNOWN_ORACLE"
    UNKNOWN_EXECUTION = "UNKNOWN_EXECUTION"
    INFEASIBLE_PROVED = "INFEASIBLE_PROVED"
    FLAKY = "FLAKY"
    BLOCKED_EXTERNAL = "BLOCKED_EXTERNAL"
    UNSUPPORTED = "UNSUPPORTED"


class LedgerStatus(StrEnum):
    ENUMERATED = "ENUMERATED"
    PROVED_INFEASIBLE = "PROVED_INFEASIBLE"
    PRESERVATION_ONLY = "PRESERVATION_ONLY"
    FRONTIER = "FRONTIER"


class ChallengeTerminalStatus(StrEnum):
    PENDING = "PENDING"
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN_ORACLE = "UNKNOWN_ORACLE"
    UNKNOWN_EXECUTION = "UNKNOWN_EXECUTION"
    INFEASIBLE_PROVED = "INFEASIBLE_PROVED"
    FLAKY = "FLAKY"
    BLOCKED_EXTERNAL = "BLOCKED_EXTERNAL"
    UNSUPPORTED = "UNSUPPORTED"


class RequirementAuthorityClass(StrEnum):
    HARD = "HARD"
    DERIVED = "DERIVED"
    HYPOTHESIS = "HYPOTHESIS"
    PRESERVATION = "PRESERVATION"


class Decision(StrEnum):
    COMMIT = "COMMIT"
    ROLLBACK = "ROLLBACK"
    ENVIRONMENT_BLOCKED = "ENVIRONMENT_BLOCKED"


class ControllerPhase(StrEnum):
    SEMANTIC = "SEMANTIC"
    GRAPH_BUILD = "GRAPH_BUILD"
    INCUMBENT_CLOSE = "INCUMBENT_CLOSE"
    CORE_SELECT = "CORE_SELECT"
    INTENT_SELECT = "INTENT_SELECT"
    GENERATOR_REVISE = "GENERATOR_REVISE"
    DIFF_RECONCILE = "DIFF_RECONCILE"
    DICC_VALIDATE = "DICC_VALIDATE"
    TRANSITION_GATE = "TRANSITION_GATE"
    COUNTEREXAMPLE_FEEDBACK = "COUNTEREXAMPLE_FEEDBACK"
    ROOT_RECOVERY = "ROOT_RECOVERY"
    ABLATE = "ABLATE"
    SEALED = "SEALED"
